# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS AMCAXRender::AMCAXRender)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target AMCAXRender::AMCAXRender
add_library(AMCAXRender::AMCAXRender SHARED IMPORTED)

# Import target "AMCAXRender::AMCAXRender" for configuration "Debug"
set_property(TARGET AMCAXRender::AMCAXRender APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(AMCAXRender::AMCAXRender PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/Debug/AMCAXRender.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "AMCAXCommon;AMCAXPart;AMCAXStep;AMCAXPm::AMCAXPm"
  IMPORTED_LOCATION_DEBUG "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/Debug/AMCAXRender.dll"
  )

# Import target "AMCAXRender::AMCAXRender" for configuration "Release"
set_property(TARGET AMCAXRender::AMCAXRender APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(AMCAXRender::AMCAXRender PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/Release/AMCAXRender.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "AMCAXCommon;AMCAXPart;AMCAXStep;AMCAXPm::AMCAXPm"
  IMPORTED_LOCATION_RELEASE "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/Release/AMCAXRender.dll"
  )

# Import target "AMCAXRender::AMCAXRender" for configuration "MinSizeRel"
set_property(TARGET AMCAXRender::AMCAXRender APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(AMCAXRender::AMCAXRender PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/MinSizeRel/AMCAXRender.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "AMCAXCommon;AMCAXPart;AMCAXStep;AMCAXPm::AMCAXPm"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/MinSizeRel/AMCAXRender.dll"
  )

# Import target "AMCAXRender::AMCAXRender" for configuration "RelWithDebInfo"
set_property(TARGET AMCAXRender::AMCAXRender APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(AMCAXRender::AMCAXRender PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/RelWithDebInfo/AMCAXRender.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "AMCAXCommon;AMCAXPart;AMCAXStep;AMCAXPm::AMCAXPm"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/jenkins/workspace/amcax-render_main/build/Debug/RelWithDebInfo/AMCAXRender.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
