/// @file      BRepIntCurveSurface.hpp
/// @brief     Class of computing intersection points for a curve and a shape which contains faces.
/// @copyright Copyright (c) 2023 Hefei Jiushao Intelligent Technology Co., Ltd. All rights reserved.
/// @par       This file is part of AMCAX kernel.
#pragma once
#include <vector>

#include <common/BoundingBox3.hpp>
#include <intersect/IntCurveSurfacePoint.hpp>
#include <math/LineT.hpp>
#include <topology/TopoShape.hpp>

namespace AMCAX
{
#ifndef DOXYGEN_SKIP
class AdaptorGeom3Curve;
class BRepIntFaceSurface;
class IntCurveSurfaceIntersection;
class TopoFace;
#endif

/// @brief Class of computing intersection points for a curve and a shape which contain face.
/// The intersection points on the edges of the shape are stored separately in their faces without deduplication check
class BRepIntCurveSurface
{
public:
	/// @brief Default constructor
	AMCAX_API BRepIntCurveSurface();

	/// @brief Perform the algorithm from a curve and a shape
	/// @param shape The shape
	/// @param curve The curve
	/// @param tol The tolerance used for the classification
	AMCAX_API void Perform(const TopoShape& shape, const AdaptorGeom3Curve& curve, double tol);

	/// @brief Perform the algorithm from a line and a shape
	/// @param shape The shape
	/// @param line The line
	/// @param tol The tolerance used for the classification
	AMCAX_API void Perform(const TopoShape& shape, const Line3& line, double tol);

	/// @brief Perform the algorithm from a ray and a shape and get point closest to the starting point of the ray.
	///	@details All intersections that are less than the tolerance from the start point of the ray will be rejected
	/// @param shape The shape
	/// @param rayLine The ray generated by the position and direction of input Line3
	/// @param tol The tolerance used for the classification
	/// @param rejectTol The tolerance used to reject intersections near the starting point of ray
	AMCAX_API void PerformFirstPoint(const TopoShape& shape, const Line3& rayLine, double tol, double rejectTol = -1);

	/// @brief Perform the algorithm from a curve and a shape and get point closest to the starting of the curve
	/// @param shape The shape
	/// @param curve The curve
	/// @param tol The tolerance used for the classification
	AMCAX_API void PerformFirstPoint(const TopoShape& shape, const AdaptorGeom3Curve& curve, double tol);

	/// @brief Perform the algorithm to check if a line intersects with a shape.
	/// @param shape The shape
	/// @param line The line
	/// @param tol The tolerance used for the classification
	/// @return true if the line intersects with the shape
	AMCAX_API bool PerformIsIntersection(const TopoShape& shape, const Line3& line, double tol);

	/// @brief Perform the algorithm to check if a curve intersects with a shape.
	/// @param shape The shape
	/// @param curve The curve
	/// @param tol The tolerance used for the classification
	/// @return true if the curve intersects with the shape
	AMCAX_API bool PerformIsIntersection(const TopoShape& shape, const AdaptorGeom3Curve& curve, double tol);

	/// @brief Load shape and initialize the faces
	/// @param shape The shape
	/// @param tol The tolerance used for the classification
	AMCAX_API void Load(const TopoShape& shape, double tol);

	/// @brief Load multiple shapes and initialize all faces
	/// @param shapes The multiple shapes
	/// @param tol The tolerance used for the classification
	AMCAX_API void Load(const std::vector<TopoShape>& shapes, double tol);

	/// @brief Perform the algorithm to find intersections of specified curve with loaded shape
	/// @param curve The curve
	AMCAX_API void Perform(const AdaptorGeom3Curve& curve);

	/// @brief Perform the algorithm to find intersections point closest to the starting of the curve with loaded shape.
	/// @param curve The curve
	AMCAX_API void PerformFirstPoint(const AdaptorGeom3Curve& curve);

	/// @brief Perform the algorithm to find intersections point closest to the starting of the ray with loaded shape.
	/// @details All intersections that are less than the tolerance from the start point of the ray will be rejected
	/// @param rayLine The ray generated by the position and direction of input Line3
	/// @param rejectTol The tolerance used to reject intersections near the starting point of ray
	AMCAX_API void PerformFirstPoint(const Line3& rayLine, double rejectTol = -1);

	/// @brief Perform the algorithm to check if the specified curve intersects with the loaded shape.
	/// @param curve The curve
	/// @return true if the curve intersects with the shape
	AMCAX_API bool PerformIsIntersection(const AdaptorGeom3Curve& curve);

	/// @brief Get the number of intersection point
	/// @return The numebr of intersection point
	[[nodiscard]] AMCAX_API int NPoints() const;

	/// @brief Get the intersection point at a given index
	/// @param index The index
	/// @return The intersection point
	[[nodiscard]] AMCAX_API const IntCurveSurfaceIntersectionPoint& IntPoint(int index) const;

	/// @brief Get the intersection geometric point at a given index
	/// @param index The index
	/// @return The intersection geometric point
	[[nodiscard]] AMCAX_API const Point3& Point(int index) const;

	/// @brief Get the U parameter of the intersection point at a given index
	/// @param index The index
	/// @return The U parameter of the intersection point on the face surface
	[[nodiscard]] AMCAX_API double U(int index) const;

	/// @brief Get the V parameter of the intersection point at a given index
	/// @param index The index
	/// @return The V parameter of the intersection point on the face surface
	[[nodiscard]] AMCAX_API double V(int index) const;

	/// @brief Get the W parameter of the intersection point at a given index
	/// @param index The index
	/// @return The W parameter of the intersection point on the curve
	[[nodiscard]] AMCAX_API double W(int index) const;

	/// @brief Get the classification state of the intersection point at a given index
	/// @param index The index
	/// @return The classification state of the intersection point on the face
	[[nodiscard]] AMCAX_API StateType State(int index) const;

	/// @brief Get the face where the intersection point belongs at a given index
	/// @param index The index
	/// @return The face where the intersection point belongs
	[[nodiscard]] AMCAX_API const TopoFace& Face(int index);

	/// @brief Get the face surface normal of the intersection point at given index
	/// @param[in] index The index
	/// @param[out] norm The surface normal(with face Orientation) of the intersection point
	/// @return true if surface have normal in intersection point;
	AMCAX_API bool SurfaceNormal(int index, Direction3& norm);

protected:
#ifndef DOXYGEN_SKIP

	void InitShapeBoxs();

	void FindAllSolution();

	void FindOneSolution();

	void FindFirstSolution(double rejectTol = -1);

	int FindSolutionPoints(int iface);

	void Clear();

#endif

private:
	double mTolerance;
	std::shared_ptr<AdaptorGeom3Curve> mCurve;
	std::shared_ptr<IntCurveSurfaceIntersection> mIntercs;
	std::vector<std::shared_ptr<BRepIntFaceSurface>> mFaces;

	std::vector<int> intFaces;
	std::vector<StateType> intPointsState;
	std::vector<IntCurveSurfaceIntersectionPoint> intPoints;
};
} // namespace AMCAX
