/// @file      MakeEvolved.hpp
/// @brief     Class of making evolved algorithm
/// @copyright Copyright (c) 2023 Hefei Jiushao Intelligent Technology Co., Ltd. All rights reserved.
/// @par       This file is part of AMCAX kernel.
#pragma once
#include <math/GeometryMacros.hpp>
#include <modeling/MakeShape.hpp>

namespace AMCAX
{
#ifndef DOXYGEN_SKIP
class BRepFillEvolved;
class BRepFillAdvancedEvolved;
class TopoWire;
class TopoShape;
#endif

/// @brief Class of making evolved algorithm
/// @details Evolve the profile (planar wire) along the spine (planar closed wire or planar face with a closed wire) to obtain a shell or a solid.
///          The difference between the evolved shape and MakePipe (MakePipeShell) shape is
///          that the first point of the swept profiles always lie on the medial curve of the wire or center point of the wire.
///          For example, a cone is made by evolving a line profile along a circle spine;
///          A tent is made by evolving a part of ellipse along a rectangle spine;
///          A mountain is made by evolving a part of ellipse along a bspine spine (the foot of the mountain);
class AMCAX_CLASS_API MakeEvolved : public MakeShape
{
public:
	/// @brief Construct an evolved shape by sweeping the profile along the spine
	/// @param spine Spine, a closed planar wire or a face with a closed planar wire
	/// @param profile Profile, planar wire
	/// @param joinType Strategy of dealing with discontinuities of the spine. Currently only Arc supported.
	/// @param isAxeProf If true, the referential coordinate system is global coordinate system.
	///                  If false, the origin is the closest point to the profile of the spine, the z axis is the normal to the spine plane and the x axis is the tangent of the curve on the origin.
	/// @param isSolid The evolved shape is solid or shell
	/// @param isProfOnSpine If true, the profile must connect with the spine
	/// @param tol Tolerance
	/// @param isVolume If true, removing self intersections by boolean algos.
	/// @param isParallel Run in parallel, currently only false supported.
	AMCAX_API MakeEvolved(const TopoShape& spine, const TopoWire& profile, JoinType joinType = JoinType::Arc, bool isAxeProf = true, bool isSolid = false, bool isProfOnSpine = false, double tol = 0.0000001, bool isVolume = false, bool isParallel = false);

	AMCAX_API void Build() override;

	/// @brief Get shapes generated by the subshape spine and the subshape profile
	/// @param spine The spine shape
	/// @param profile The profile shape
	[[nodiscard]] AMCAX_API const std::list<TopoShape>& GeneratedShapes(const TopoShape& spine, const TopoShape& profile) const;

	/// @brief Get top face (only available if isSolid is true)
	[[nodiscard]] AMCAX_API const TopoShape& Top() const;

	/// @brief Get bottom face (only available if isSolid is true)
	[[nodiscard]] AMCAX_API const TopoShape& Bottom() const;

private:
	std::shared_ptr<BRepFillEvolved> evolved;
	std::shared_ptr<BRepFillAdvancedEvolved> volume;
};
} // namespace AMCAX
