/// @file      MakePipe.hpp
/// @brief     Class of making pipe algorithm
/// @copyright Copyright (c) 2023 Hefei Jiushao Intelligent Technology Co., Ltd. All rights reserved.
/// @par       This file is part of AMCAX kernel.
#pragma once
#include <geomAlgo/GeomFillStyle.hpp>
#include <modeling/MakeSweep.hpp>

namespace AMCAX
{
#ifndef DOXYGEN_SKIP
class BRepFillPipe;
class TopoWire;
class TopoShape;
#endif

/// @brief Class of make pipe algorithm
/// @details Sweep the profile along the spine (at least G1 continuity).
///          If the spine and the profile do not contact or match directions to sweep, the spine will be translated.
///          The strategy of profile rotation along spine is defined by GeomFillTrihedron and the default strategy is CorrectedFrenet.
class AMCAX_CLASS_API MakePipe : public MakeSweep
{
public:
	/// @brief Make pipe by sweeping the profile along the spine. Mode is set CorrectedFrenet and forceApproxC1 is set false.
	/// @param spine The spine which can be open or closed but must be at least G1 continuity.
	/// @param profile The profile to be swept. It is ok to be 3d or 2d, close or open.
	AMCAX_API MakePipe(const TopoWire& spine, const TopoShape& profile);

	/// @brief Make pipe by sweeping the profile along the spine
	/// @param spine The spine which can be open or closed but must be at least G1 continuity.
	/// @param profile The profile to be swept. It is ok to be 3d or 2d, close or open.
	/// @param mode The sweeping strategy
	/// @param forceApproxC1 Is the pipe forced to be C1 continuity. If the result is not C1, approx is applied.
	AMCAX_API MakePipe(const TopoWire& spine, const TopoShape& profile, GeomFillTrihedron mode, bool forceApproxC1 = false);

	AMCAX_API void Build() override;

	/// @brief Get the first shape
	/// @return The first shape
	[[nodiscard]] AMCAX_API TopoShape FirstShape() override;

	/// @brief Get the last shape
	/// @return The last shape
	[[nodiscard]] AMCAX_API TopoShape LastShape() override;

	[[nodiscard]] AMCAX_API const std::list<TopoShape>& Generated(const TopoShape& s) override;

	/// @brief Get a specified part of the generated pipe face
	/// @param spine Part of spine to select which part is needed
	/// @param profile Part of profile to select which part is needed
	/// @return A part of pipe face generated by sspine and sprofile
	[[nodiscard]] AMCAX_API TopoShape Generated(const TopoShape& spine, const TopoShape& profile);

	/// @brief Get the error on surface
	/// @return The error on surface
	[[nodiscard]] AMCAX_API double ErrorOnSurface() const;

private:
	const BRepFillPipe& Pipe() const;

	std::shared_ptr<BRepFillPipe> fillPipe;
};
} // namespace AMCAX
